export const SHORT_FORM_EXPRESSION =
  "QmTR49sVKEUam1oUnf2UyeDKcsmXnP7F5fJThcXYqG8c8S";

export const PROFILE_EXPRESSION =
  "QmTCKNzoXpQrrPfXEyHYT241HGgGpHd3Uq3HBzSVXLY99R";

export const GROUP_EXPRESSION =
  "QmPxdiSRmMkPENeZpAMr4roFwFKVNitGMZtjiEkQxXwipF";
