export const AUDIO_VIDEO_FORM_EXPRESSION =
  "QmZcBnibiYAqe7Nq3qrEwjgGmg7dknkExXB4KzzUhniavQ";

export const ICE_EXPRESSION_OFFICIAL = 
  "QmSwqKKMaWXd1UW3eyBU9gBk7wz82cwg8CB8wsH94cDJpj"

export const SHORT_FORM_EXPRESSION =
  "QmVDh4jd75BgPgiV6Lttjm7xQ8JQBkQJtqwBcPn4xZyXgP";

export const PROFILE_EXPRESSION =
  "QmTTYB2E8tXRDt5ZHSMbVuZ71jZDzWJM6U9YcL86aheoz8";

export const GROUP_EXPRESSION =
  "Qmd7Wssoo9kwzdqJBE5aSE7YyVJ4TmD5mqX7L8yffR8MU7";
