export const SHORT_FORM_EXPRESSION =
  "QmVDh4jd75BgPgiV6Lttjm7xQ8JQBkQJtqwBcPn4xZyXgP";

export const PROFILE_EXPRESSION =
  "QmSuJWiQFYWba6siE1fcKcP3yTYE7BssGg22UKShWGMVgp";

export const GROUP_EXPRESSION =
  "Qmd7Wssoo9kwzdqJBE5aSE7YyVJ4TmD5mqX7L8yffR8MU7";
